cmake_minimum_required(VERSION 4.2)
project(GFG_Exercises)

set(CMAKE_CXX_STANDARD 20)

add_executable(GFG_Exercises
        GFG_Arrays/GFG_solve1.cpp
        GFG_Arrays/GFG_solve2.cpp
        GFG_Arrays/GFG_solve3.cpp
        GFG_Arrays/GFG_solve4.cpp
        GFG_Arrays/GFG_solve5.cpp
        GFG_Arrays/GFG_solve6.cpp
        CSET/CSET_solve1.cpp
        CSET/CSET_solve2.cpp
        CSET/CSET_solve3.cpp
        CodeForces/CF_one.cpp
        GFG_MATHS/Math_solve1.cpp
        GFG_MATHS/Math_solve2.cpp
        GFG_MATHS/Math_solve3.cpp
        GFG_MATHS/Math_solve4.cpp
        GFG_MATHS/Math_solve5.cpp
        GFG_MATHS/Math_solve6.cpp
        Concept/Graph.cpp
        GFG_MATHS/Math_solve8.cpp
        GFG_MATHS/Math_solve9.cpp
        GFG_MATHS/Math_solve10.cpp
        CSET/CSES_solve4.cpp
        CSET/CSES_solve5.cpp
        CSET/CSES_solve6.cpp
        CSET/CSES_solve7.cpp
        AT_CODER/ATC_solve1.cpp
        CSET/CSES_solve8.cpp
        GFG_MATHS/Math_Solve11.cpp
)
