cmake_minimum_required(VERSION 4.2)
project(GFG_Exercises)

set(CMAKE_CXX_STANDARD 20)

add_executable(GFG_Exercises
        GFG_Arrays/GFG_solve1.cpp
        GFG_Arrays/GFG_solve2.cpp
        GFG_Arrays/GFG_solve3.cpp
        GFG_Arrays/GFG_solve4.cpp
        GFG_Arrays/GFG_solve5.cpp
        GFG_Arrays/GFG_solve6.cpp
        CSET/CSET_solve1.cpp
        CSET/CSET_solve2.cpp
        CSET/CSET_solve3.cpp
        CodeForces/CF_one.cpp
        GFG_MATHS/Math_solve1.cpp
        GFG_MATHS/Math_solve2.cpp
        GFG_MATHS/Math_solve3.cpp
        GFG_MATHS/Math_solve4.cpp
        GFG_MATHS/Math_solve5.cpp
        GFG_MATHS/Math_solve6.cpp
)
